Use PUBLIC + BUILD_INTERFACE instead of PRIVATE
The difference between PRIVATE and PUBLIC + BUILD_INTERFACE is next:

* PRIVATE only used for lua_lib target's sources (i.e. when compiling lgc.c or
  llex.c). PRIVATE not used after target installed.

* PUBLIC used for both target's sources (still for lgc.c or llex.c) but also
  for any target that do link 'lua_lib', e.g. lua executable - lua.c source.
  But since 'src' should not be used after installation => include path should
  be limited by `BUILD_INTERFACE` generator expression.

Error can be reproduced by moving executables 'lua' and 'luac' to the separate
directory. When PRIVATE used there will be no include path added to 'lua' and
compilation will fail:

/.../lua.c:9:21: fatal error: lprefix.h: No such file or directory
 #include "lprefix.h"
                     ^